version: '3'

services:

  app:
    image: rohailiqbal/user-data-service
    ports:
      - 8080:8080
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      REDIS_HOST: redis
      REDIS_PORT: 6379

  mongodb:
    image: mongo
    ports:
      - 27017:27017

  redis:
    image: redis
    ports:
      - 6379:6379